### ISSUE TITLE
I Want Take Over This Project

### ISSUE THREAD

**Issue by ghost** [nicoschuele/railsbricks#1]
Dear Sir,
  I am a new user of ruby&rails, and want to take over this project.
  On the one hand, I want to have a project as a test and exercise; on the other hand, I really like this project and want to contribute.
  But there are some problems that you should know. First, I want to have a new release which under The Apache License V2.0, however, it under GPL now.Second, I am a Coder but have poor English Skil, if I take over it, some documents could be written by my mother language.
   If you would like to let me take over it, I believe that I could take care of it.
   Looking forward to your early reply.
   Best wishes.
                                                                            Yours,
                                                                            PsiACE

**Comment by nicoschuele** [comment]
Hi. No. Thanks.

**Comment by ghost** [comment]
Okay, but I want to know why.

**Comment by nicoschuele** [comment]
Because your Github is empty. Have some code to show? I'm not giving a project I worked on for 4 years to any random stranger.

**Comment by ghost** [comment]
Okay, thank you for your kindness. I'm sorry to have bothered.
