### ISSUE TITLE
How to add a test suite for RailsBricks itself?

### ISSUE THREAD

**Issue by nicoschuele** [nicoschuele/railsbricks#66]
Going forward, RailsBricks needs to have a test suite built-in. Just recently, I updated the Redcarpet gem used by the Post feature only to notice after it was pushed to rubygems that the updated Redcarpet broke a feature.

I do believe in testing but I lack the experience to design a test suite that would be adapted to RailsBricks so contributions and pointers are needed.

What should be tested, then?

* RailsBricks builds Rails apps. The whole process of generating a valid app should be tested.
* The generated apps themselves need to be tested.

At the moment, when pushing a new release of RailsBricks, I test manually the generation on both OS X and Linux: that correct gems get installed, that the menu selections are properly handled during generation, and so on. When the Rails app is generated, I test it manually: I can create a new user, emails get sent properly, etc... . Unfortunately, I fail to see how this whole process could be automatized.

Where to start?

**Comment by dmitriy-kiriyenko** [comment]
Try consulting (suspenders)[https://github.com/thoughtbot/suspenders/tree/master/spec] – their testing looks consistent and robust.
