### ISSUE TITLE
Video appears to be corrupt

### ISSUE THREAD

**Issue by brandondrew** [nicoschuele/railsbricks#71]
The video on railsbricks.net will not finish.  I've tested on both Chrome and Firefox, and see slightly different behavior on each:

On Chrome it forcibly exits fullscreen mode and the browser page dies around 3:10.  I can skip past 3:10 and get it to go until around 3:26, but I haven't gotten it to go past that without seeing this behavior.
![image](https://cloud.githubusercontent.com/assets/9854/5593778/03d8d2e8-91f5-11e4-948a-4fdf7e202748.png)

On Firefox it also forcibly exits fullscreen mode and the movie goes black and becomes unusable (even if you try to go back to an earlier point it won't display anything or even move the play head, although it still displays the progress bar and shows you the time when you mouse over the progress bar).  I can't get it past 3:07 on Firefox.

![image](https://cloud.githubusercontent.com/assets/9854/5593782/2d4f5cdc-91f5-11e4-9ccd-c829433d58f3.png)

(Sorry if this is not the ideal place to file this issue.  I couldn't find a repo for the site, or a gh-pages branch, so this seemed like the best place I could find.)

**Comment by nicoschuele** [comment]
Strange... Just tried it on OS X with Chrome, Safari and Firefox as well as on Windows with Chrome with no issues. Maybe one of your plug-ins? What about other Vimeo videos?

**Comment by nicoschuele** [comment]
Alright, tried from different machines and different people. All seems to be ok. I guess there's something wrong with your connection and/or plugins.

Thanks for the notification, though!
