### ISSUE TITLE
railsbricks should setup internationalizable app (i18n)

### ISSUE THREAD

**Issue by fwolfst** [nicoschuele/railsbricks#75]
For me it would be great if railsbricks ships out with a basic I18n setup (use `t()`, include rails-i18n, devise-i18n, language switcher).

As always, adding i18n later on is more cumbersome than right from the beginning. I could offer to deliver a basic PR that uses i18n at least in some places.

Don't get me wrong on the "should" in the title.

**Comment by nicoschuele** [comment]
I leave this one open with a *contribution needed* tag as I won't have time to implement it. 

It should be then implemented everywhere, work with all the possible templates, Devise, etc... as I won't merge a half-made feature into a RailsBricks release.

**Comment by fwolfst** [comment]
Hi Nico,

Cool. Can you sketch me the minimum features you would like to see?

E.g. 2 languages, language switcher, language scoped routes (http://myhost.com/en/posts/my-post), all strings translated ...

**Comment by nicoschuele** [comment]
Alright...

* all strings should be ready for translation. Menus, footer, forms, `placeholder` tags,  etc.
* no need for a language switcher, people can code that themselves quickly the way they want it, providing all the strings are ready to be updated
* no need for translation now. Just English.
* default routes map to english and scoped routes will be `domain.com/en/...`

It is important to allow people to choose if they want their application ready for translation or not which means adding a step to the new app wizard. It seems logical to me to place this menu right after the section on UI choices.

How does that sound?

**Comment by fwolfst** [comment]
Sounds good, although I guess the configurability might be the hardest part - I guess it means having two templates for every step, one with i18n, the other without. I will take a quick dive and will see if and when its feasible for me to dive that deep.

**Comment by nicoschuele** [comment]
I don't think two templates is the way to go. Makes it harder to maintain and duplicates code. For these cases, RailsBricks uses placeholder strings and replaces them using regexp depending on the user's choices.

**Comment by fwolfst** [comment]
It's not off my list, your approach sounds reasonable.

**Comment by fwolfst** [comment]
I added a menu entry. Currently it defaults to "Yes" for i18n and does nothing but add rails-i18n and devise-i18n if respective options were selected. See https://github.com/fwolfst/railsbricks/tree/i18n and tell me what you think. There is also a minor refactoring cleanup. Please give some feedback, I can then formulate a PR.

**Comment by fwolfst** [comment]
Okay, I think the way to go would be: update all views to really use `<%= t('..') %>` and provide translations in `config/locales/en.yml`. Then, if no i18n selection was made, render the templates with the translation. Although this should be possible using erb and stuff, I think its easy enough to do "by hand". *It feels like a super-stupid thing to "untranslate", though.* Anyway, I'll see what we can do. Also, the initial locale/translation-file layout would be really plain.

**Comment by nicoschuele** [comment]
Super busy today but will have a look this week-end. Thanks for your work so far.

I think that if a user isn't using i18n, the views shouldn't show `<%= t('..') %>` but `<%= "the text" %>` in order to allow people to type static text content directly within the views and not in the translation file, though.

Regarding the clean up of the copy-paste thing, can you submit an individual PR, please? Thanks.

**Comment by fwolfst** [comment]
No problem, will be busy, too.
I opt for non-erb strings in case of non-i18n-apps and pushed something along these lines forward (in my fork, i18n branch). Still lots of strings to replace and adjust routes and config. Also, at the moment, t('')-Strings are replaced irrespective of the actual user choice (WIP!). The en.yml layout needs some love and irrelevant stuff must be excluded (e.g. if the user didnt want a Post model, no Post-related translations). I'd be happy to finish that feature, but cannot promise to do so.

**Comment by fwolfst** [comment]
Time passed, but the issue is not lost (some steps are visible in my branch). I wonder, as railsbricks4 does not seem to be miles away, how does i18n will be included in the pack? And what could I do to include it myself?

I would suggest to open a branch, or if its dev-from-scratch, a new repository.

**Comment by nicoschuele** [comment]
Hey. At the moment, the next version of RailsBricks is in private development (target release for end of Summer) so not much you can do here. The good news is that internationalization is handled. I won't be adding any new feature to RailsBricks 3 and it will be in maintenance mode until the next version is released. Closing the issue too. Thanks!

**Comment by fwolfst** [comment]
Awesome, thank you very much. Quite some minutes of vim use for the trash-can, but spending time with a partner is never lost time, is it?
