### ISSUE TITLE
Railsbricks on Homebrewed Ruby

### ISSUE THREAD

**Issue by balaputradewa** [nicoschuele/railsbricks#77]
I installed railsbricks on OS X 10.10 on brewed Ruby. Whenever I generate new apps, the bundler couldn't find gems that installed in my machine and build ruby 2.2.0 on ./vendor/bundle. 

Is it because my ruby version is 2.2.1?

**Comment by nicoschuele** [comment]
Yep. Ruby 2.2.1 is not yet supported. Will do it this weekend.
