### ISSUE TITLE
Add support for Grape API

### ISSUE THREAD

**Issue by MiroslavCsonka** [nicoschuele/railsbricks#88]
+ add structure from http://codetunes.com/2014/introduction-to-building-apis-with-grape/

**Comment by nicoschuele** [comment]
I am currently working on a RailsBricks-like app builder specifically for making API's using Rails API. I won't implement this within RailsBricks.

**Comment by bricesanchez** [comment]
@nicoschuele Do you have any update for your RailsBricks-like app builder for API's ? Do you want to OSS it ?

**Comment by nicoschuele** [comment]
Hey. This will be handled in the next version of RailsBricks when support for Rails 5 is added. Rails 5 includes rails api. 

I don't plan to OSS my current tool.

**Comment by bricesanchez** [comment]
@nicoschuele i understand, thanks for your awesome work on railsbricks :)
