### ISSUE TITLE
Features/Reuqirements/Future - v4 or maybe strategy change?

### ISSUE THREAD

**Issue by frankis** [nicoschuele/railsbricks#90]
Hi Nico, as you are busy and seem to be very smart, I am not going to explain every of the following topics in detail but should you plan visiting hamburg **in the very near future** your hotel (2 nights) is paid by me in return for 2-3 hours of your time.

1. Pls. drop the idea of integrating a discussion forum but add an option to integrate disqus on posts
2. I have read in an issue ticket here at GH about localization for the backend. I recommend focusing on integrating an option to allow localized posts & pages but keep the backend in english
3. Integrating app deploy to digital ocean (or similar) would be great, but I would prefer a clean workflow for local, stage and prod environments and related "app publishing" features, incl. an option to fetch a copy of the live db for local dev and staging.
4. Pls. add oauth option to integrate login with twitter, fb, g+,... ON TOP of "standard" loging already provided
5. Pls. add option to allow inserting bing api key
6. Pls. add option for author bio & pages
7. pls. add option to create (or not) slug, permalink, no-index checkbox with posts and pages
8. pls. add option for different frameworks such as foundation or materilaize
9. add option for social specific meta in headers
10. pls. add support for local timezone on setup

**Comment by nicoschuele** [comment]
Hey,

Thanks for your suggestions. Although I don't agree with all of them, I will keep some in mind as I started to draft the features for version 4. For example, timezones are something I'm working on at the moment. V4 will be *quite* different from V3, especially regarding deployment capabilities (mostly due to Heroku's changes in pricing).
