### ISSUE TITLE
doc request: please explain problem with Postgres.app

### ISSUE THREAD

**Issue by brandondrew** [nicoschuele/railsbricks#92]
I'm confused as to the problem with using Postgres.app.  When building a new app, we get the message that we need to use the Homebrew version of Postgres, because of the changing location of `pg_config` with Postgres.app:

> If you are on OS X, I struggle with the Postgres.app as the location of
> pg_config keeps changing between versions. If you want to use PostgreSQL,
> you'll have to use a full install which you can get through Homebrew by running
> 'brew install postgresql'.

but as long as we manage our `$PATH` properly, so that any shell commands you execute find the right `pg_config`, what would the problem be?

Thanks in advance for any explanation you can give.

**Comment by nicoschuele** [comment]
Of course, if you manage your $PATH properly, you can use Postgres.app. But previous versions of RailsBricks have shown that most people don't. They just install Postgres.app, start it, launch RailsBricks and it fails. That's why I added this warning. Does that make sense?
